### ISSUE TITLE
is_feed was called incorrectly

### ISSUE THREAD

**Issue by keskistok** [Brain-WP/Hierarchy#24]
PHP Notice:  is_feed was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.) in /wp-includes/functions.php on line 5663

**Comment by gmazzap** [comment]
`is_feed` is called from `QueryTemplate::mainQueryTemplateAllowed`.

Like the error message says, the issue does not depend on the funcion being wrong, but it being called early.

`QueryTemplate::mainQueryTemplateAllowed` is never called by the library, it must be called "manually".
If you look at the README, the function call is are always hooked in actions like `template_redirect`, and if you'll do that as well there will be no notice, because at that point the main query is there.
