### ISSUE TITLE
Let the LoaderFactory decide whether the instance is shared or not

### ISSUE THREAD

**Issue by schlessera** [Brain-WP/Hierarchy#9]
In the `CascadeAggregateTemplateLoader`, when you're dealing with a factory, you use the factory once and then replace it by the instance it returned: https://github.com/Brain-WP/Hierarchy/blob/dev/src/Loader/CascadeAggregateTemplateLoader.php#L72

I think that you should remove that line, as the Factory should decide for itself whether it wants to use 1 shared instance, or whether it needs to create a fresh instance for each request.

**Comment by gmazzap** [comment]
The factory does not receive arguments, so the loader is stateless.

Moreover, the reason to pass a factory instead of an already formed instance is the fact that instance creation is expensive.

This is why I went opinionated deciding that the factory is called once.

But I get your point, and I see that if a fresh instance is needed for some reason there's no way to do that, but a factory has the possibility to "cache" the instance, so I agree with you right and I'm going to merge ee05290.

Thanks.
